name: Assign

on:
  pull_request:
    types: [opened, closed]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign
        uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
