name: Auto Assign

on:
  pull_request:
    types: [opened, closed]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          merged-comment: "Thank you for your contribution! :bow:"
